{% set name = "git-annex" %}
{% set version = "" %}
{% set sha256 = "7.20190219" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://hackage.haskell.org/package/git-annex-7.20190219/git-annex-7.20190219.tar.gz
  sha256: {{ sha256 }}

build:
  number: 4
  skip: True  #  [osx]

requirements:
  build:
    - stack >=1.3.2
    - gmp
    - zlib
    - perl
    - ncurses
    - gnupg
    - git
    - libmagic
    - libgsasl
    - chrpath
    - libxml2
    - gnutls
    - sqlite

  run:
    - viennarna ==2.3.3
    - rnaz ==2.1
    - locarna ==1.9.1
    - infernal ==1.1.2
    - rnacode ==0.3
    - gmp
    - perl
    - zlib
    - openssl
    - ncurses
    - gnupg
    - git
    - libmagic
    - libgsasl
    - chrpath
    - libxml2
    - gnutls
    - sqlite

test:
  commands:
    - git-annex version
    - git-annex test

about:
  home: http://rna.tbi.univie.ac.at/rnalien/tool
  license: GPL-3
  summary: A tool for unsupervised construction of RNA family models

extra:
  identifiers:
    - biotools:RNAlien
    - doi:10.1093/nar/gkw558
