{% set name = "git-annex" %}
{% set version = "7.20190219" %}
{% set sha256 = "82f3c10fe96141b1564bfc894a36c0e53bdf6843f09782c380d1a616bf96c104" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://hackage.haskell.org/package/git-annex-7.20190219/git-annex-7.20190219.tar.gz
  sha256: {{ sha256 }}

build:
  number: 5
  skip: True  #  [osx]

requirements:
  build:
    - stack >=1.3.2
    - gmp
    - zlib
    - perl
    - ncurses
    - gnupg
    - git
    - libmagic
    - libgsasl
    - chrpath
    - libxml2
    - gnutls
    - sqlite
    - rsync
    - coreutils
    - binutils

  run:
    - gmp
    - perl
    - zlib
    - openssl
    - ncurses
    - gnupg
    - git
    - libmagic
    - libgsasl
    - chrpath
    - libxml2
    - gnutls
    - sqlite
    - libgcc-ng
    - libstdcxx-ng
    - rsync
    - coreutils
    - binutils

test:
  commands:
    - git-annex version
    - git-annex test

about:
  home: http://git-annex.branchable.com
  license: GPL-3
  summary: A tool for managing large files with git
